services:
  tg-channel-search:
    build: 
      context: ..
      dockerfile: TgChannelSearch/Dockerfile
    command: $RECOGNIZE_DB $CHANNEL_TAG
    restart: unless-stopped 
    volumes:
      - $CONFIG_DIR:/app/config
      - $DATA_DIR:/app/data
      - $RECOGNIZE_DIR:/app/recognize
